FROM python:3.10-slim-bullseye

WORKDIR /server/api

ADD api/requirements.txt .

RUN pip install -r requirements.txt

ADD data ../data

ADD api .

CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000