name: Run tests

on:
  pull_request:
    branches: 
      - develop
      - main
      
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Run python unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Install app dependencies
        run: pip install -r src/app/requirements.txt
        
      - name: Run app unit tests
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          DISPLAY=:1 SERVER_URL=${{secrets.server_url}} python -m unittest discover src/app/tests
      
      - name: Install api dependencies
        run: pip install -r src/api/requirements.txt
        
      - name: Run api unit tests
        run: |
          cd src/api
          TEST=1 python manage.py test


